### PR TITLE
Extension: userStorage incorrect type check fix in Nette\DI 2.2.3

### PR DESCRIPTION
**Pull request by TomasVotruba**
See: https://github.com/Kdyby/Console/pull/29, getting same error

### CODE REVIEW

**Comment by Majkl578** [comment]
To be honest, I don't even like the magic with replacing the service this way, but there is (or at least wasn't before) any proper way, so it was always fragile. BC break in stable release is sad, but well, we all know Nette...
Anyway this should be fixed by #5.

**Comment by TomasVotruba** [comment]
I agree with you in all points.

#5 looks fine, would you care PHPUnit for tests for 2.0/2.1/2.2? I can try prepare PR.

**Comment by Majkl578** [comment]
If you want to spend some time with that, you're welcome. :+1: Although there is not much to test. :)

**Comment by TomasVotruba** [comment]
Closing in favor of #8

**Pull request closed without merging**
