### PR TITLE
Depend on nette/* instead of nette/nette

### PR DESCRIPTION
**Pull request by Majkl578**
Ideas @fprochazka @Unlink?

### CODE REVIEW

**Comment by juniwalk** [comment]
:+1:

Just two things, you could set dependency on *doctrine/orm* instead of *kdyby/doctrine* in composer and also you can require `EntityManagerInterface` in `UserStorage`, but that is just nitpicking.

**Comment by Majkl578** [comment]
kdyby/doctrine is for tests only and EntityManagerInterface is since Doctrine 2.4 (would require dropping 2.3 support for no benefit).

**Comment by juniwalk** [comment]
I see, nevermind then. :)

**Comment by Majkl578** [comment]
No problem, thanks for input anyway! :)

**Pull request merged**
